### ISSUE TITLE
Error resolving ImageStreamTag php:7.3-ubi8

### ISSUE THREAD

**Issue by ryannix123** [sclorg/cakephp-ex#118]
Can I not use this updated image stream in OpenShift 3.11?

Reason: Error resolving ImageStreamTag php:7.3-ubi8 in namespace openshift: unable to find latest tagged image

**Comment by bparees** [comment]
> Can I not use this updated image stream in OpenShift 3.11?

i assume you mean the updated template.

to use the updated template you'll need to add the new imagestream that the updated template is looking for.  you can install the imagestream yourself, in the openshift namespace.  you can find it here:

https://github.com/sclorg/s2i-php-container/blob/master/imagestreams/php-centos.json

`oc apply -f https://github.com/sclorg/s2i-php-container/blob/master/imagestreams/php-centos.json -n openshift`

**Comment by bparees** [comment]
whoops, replace that url w/ the raw url:
https://raw.githubusercontent.com/sclorg/s2i-php-container/master/imagestreams/php-centos.json

**Comment by ryannix123** [comment]
Thanks, @bparees !

I ran ```
oc apply -f https://raw.githubusercontent.com/sclorg/s2i-php-container/master/imagestreams/php-centos.json -n openshift
imagestream.image.openshift.io/php configured
```

I assume I have to do the same thing for the updated cakephp stream?

**Comment by bparees** [comment]
cakephp isn't an imagestream, it's a template.  if you want to install it in your cluster you can pick the template you want from https://github.com/sclorg/cakephp-ex/tree/master/openshift/templates and run `oc create -f <template raw url or file> -n openshift`

**Comment by bparees** [comment]
but you don't have to install the template in your cluster to use it.  you can just reference it from disk also, using oc new-app or oc process

**Comment by ryannix123** [comment]
```
oc create -f https://raw.githubusercontent.com/sclorg/cakephp-ex/master/openshift/templates/cakephp-mysql-persistent.json -n openshift
Error from server (AlreadyExists): error when creating "https://raw.githubusercontent.com/sclorg/cakephp-ex/master/openshift/templates/cakephp-mysql-persistent.json": templates.template.openshift.io "cakephp-mysql-persistent" already exists
```
@bparees Is there a way to update the existing template?

**Comment by bparees** [comment]
oc apply should do it, or you can oc delete the existing one.

**Comment by ryannix123** [comment]
Brilliant. Thanks, @bparees !

**Comment by bparees** [comment]
yw!

**Comment by phracek** [comment]
@ryannix123 Can you please close this issue, if it is already resolved?

**Comment by ryannix123** [comment]
Yes, sorry about that!
